


# EXPERIMENT_NAME = "1A"
# DICTIONARY = ['A', 'B', 'C']
# NUMBER_OF_STATES = 3
# SEQUENCE_LENGTH = 4
# START_POSITION = [[1., 0., 0.]]
# NUMBER_OF_SAMPLES = 200
# EPOCHS = 100
# TEST_SPLIT_PCT = 0.1


# EXPERIMENT_NAME = "1B"
# DICTIONARY = ['A', 'B', 'C']
# NUMBER_OF_STATES = 4
# SEQUENCE_LENGTH = 4
# START_POSITION = [[1., 0., 0., 0.]]
# NUMBER_OF_SAMPLES = 200
# EPOCHS = 100
# TEST_SPLIT_PCT = 0.1

# EXPERIMENT_NAME = "2"
# DICTIONARY = ['A', 'B', 'C', 'D']
# NUMBER_OF_STATES = 5
# SEQUENCE_LENGTH = 5
# START_POSITION = [[1., 0., 0., 0., 0.]]
# NUMBER_OF_SAMPLES = 1500
# EPOCHS = 100
# TEST_SPLIT_PCT = 0.1

EXPERIMENT_NAME = "test_gpu"
DICTIONARY = ['A', 'B', 'C', 'D']
NUMBER_OF_STATES = 5
SEQUENCE_LENGTH = 5
START_POSITION = [[1., 0., 0., 0., 0.]]
NUMBER_OF_SAMPLES = 1500
EPOCHS = 100
TEST_SPLIT_PCT = 0.1

